/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SinkResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterSinkRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sinks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SinkResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sinks/{id}/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number | string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeadLetterResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sinks/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    q: string;
                    table?: string;
                    limit?: number | string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["SseItemOfFeedEntry"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sinks/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    fromLsn?: string;
                    reset?: boolean;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sinks/{id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sinks/{id}/dead-letters/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RetryResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        ChangeOperation: "Insert" | "Update" | "Delete";
        ColumnValue: {
            name: string;
            value: null | string;
        };
        DeadLetterResponse: {
            /** Format: int64 */
            id: number | string;
            source: string;
            /** Format: int64 */
            seq: number | string;
            table: string;
            operation: components["schemas"]["ChangeOperation"];
            key: components["schemas"]["ColumnValue"][];
            error: string;
            /** Format: int32 */
            attempts: number | string;
            /** Format: date-time */
            deadAt: string;
        };
        FeedEntry: {
            kind: components["schemas"]["FeedKind"];
            /** Format: date-time */
            at: string;
            source: string;
            table: string;
            operation: string;
            key: string;
            commitLsn: string;
            sink: null | string;
            detail: null | string;
        };
        /** @enum {unknown} */
        FeedKind: "Change" | "Conflict" | "DeadLetter";
        RegisterSinkRequest: {
            id: string;
            kind: components["schemas"]["SinkKind"];
            tables: string[];
            target: null | string;
            start: components["schemas"]["SinkStartMode"];
            startLsn: null | string;
        };
        RetryResponse: {
            /** Format: int32 */
            resolved: number | string;
            /** Format: int32 */
            stillBlocked: number | string;
        };
        SearchHit: {
            table: string;
            key: components["schemas"]["ColumnValue"][];
            row: components["schemas"]["ColumnValue"][];
        };
        SearchResponse: {
            rows: components["schemas"]["SearchHit"][];
        };
        SinkCountersResponse: {
            /** Format: int64 */
            changed: number | string;
            /** Format: int64 */
            unchanged: number | string;
            /** Format: int64 */
            conflicts: number | string;
            /** Format: int64 */
            deadLetters: number | string;
            /** Format: int64 */
            retries: number | string;
            lastError: null | string;
        };
        /** @enum {unknown} */
        SinkKind: "Postgres" | "Index" | "Webhook";
        SinkResponse: {
            id: string;
            kind: components["schemas"]["SinkKind"];
            tables: string[];
            target: null | string;
            state: components["schemas"]["SinkState"];
            /** Format: int32 */
            blockedRows: number | string;
            sources: components["schemas"]["SinkSourceResponse"][];
            counters: components["schemas"]["SinkCountersResponse"];
        };
        SinkSourceResponse: {
            source: string;
            /** Format: int64 */
            appliedSeq: number | string;
            /** Format: int64 */
            headSeq: number | string;
            startLsn: string;
            pendingLsn: null | string;
            /** Format: double */
            lagMilliseconds: number | string;
        };
        /** @enum {unknown} */
        SinkStartMode: "Beginning" | "Now" | "Lsn" | "Snapshot";
        /** @enum {unknown} */
        SinkState: "Running" | "Retrying" | "Rebuilding" | "Stopped";
        SourceResponse: {
            name: string;
            attachedTo: null | string;
            primary: null | string;
            /** Format: int64 */
            walRetainedBytes: null | number | string;
            confirmedFlushLsn: null | string;
            slotActive: boolean;
            standbys: components["schemas"]["StandbyResponse"][];
            /** Format: int64 */
            changes: number | string;
            /** Format: int64 */
            transactions: number | string;
            /** Format: int64 */
            resent: number | string;
            /** Format: date-time */
            lastCommit: null | string;
            lastError: null | string;
            /** Format: date-time */
            checkedAt: null | string;
        };
        SseItemOfFeedEntry: {
            data?: components["schemas"]["FeedEntry"];
            eventType?: null | string;
            eventId?: null | string;
            reconnectionInterval?: null | string;
        };
        StandbyResponse: {
            host: string;
            synced: boolean;
            confirmedFlushLsn: null | string;
        };
        StatsResponse: {
            /** Format: date-time */
            at: string;
            sources: components["schemas"]["SourceResponse"][];
            sinks: components["schemas"]["SinkResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
