// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Walrus.Infrastructure.Store;

#nullable disable

namespace Walrus.Infrastructure.Store.Migrations
{
    [DbContext(typeof(WalrusDbContext))]
    partial class WalrusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Walrus.Infrastructure.Store.CaptureStateRow", b =>
                {
                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<NpgsqlLogSequenceNumber>("ConfirmedLsn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("pg_lsn")
                        .HasColumnName("confirmed_lsn")
                        .HasDefaultValueSql("'0/0'::pg_lsn");

                    b.Property<long>("Epoch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("epoch");

                    b.Property<long>("LastHlc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_hlc");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Source")
                        .HasName("pk_walrus_capture_state");

                    b.ToTable("walrus_capture_state", (string)null);
                });

            modelBuilder.Entity("Walrus.Infrastructure.Store.DeadLetterRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("DeadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_key");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("event");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("SinkId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sink_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_walrus_dead_letters");

                    b.HasIndex("SinkId", "EntityKey")
                        .HasDatabaseName("ix_walrus_dead_letters_sink_id_entity_key")
                        .HasFilter("resolved_at is null");

                    b.ToTable("walrus_dead_letters", (string)null);
                });

            modelBuilder.Entity("Walrus.Infrastructure.Store.OutboxRow", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Seq"));

                    b.Property<string>("After")
                        .HasColumnType("json")
                        .HasColumnName("after");

                    b.Property<string>("Before")
                        .HasColumnType("json")
                        .HasColumnName("before");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<string[]>("ChangedColumns")
                        .HasColumnType("text[]")
                        .HasColumnName("changed_columns");

                    b.Property<NpgsqlLogSequenceNumber>("CommitLsn")
                        .HasColumnType("pg_lsn")
                        .HasColumnName("commit_lsn");

                    b.Property<DateTimeOffset>("CommitTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("commit_ts");

                    b.Property<long>("Hlc")
                        .HasColumnType("bigint")
                        .HasColumnName("hlc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("key");

                    b.Property<char>("Op")
                        .HasColumnType("char(1)")
                        .HasColumnName("op");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<long>("Xid")
                        .HasColumnType("bigint")
                        .HasColumnName("xid");

                    b.HasKey("Seq")
                        .HasName("pk_walrus_outbox");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("ix_walrus_outbox_captured_at");

                    b.HasIndex("Source", "Seq")
                        .HasDatabaseName("ix_walrus_outbox_source_seq");

                    b.HasIndex("Source", "CommitLsn", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_walrus_outbox_source_commit_lsn_ordinal");

                    b.ToTable("walrus_outbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_walrus_outbox_op", "op in ('c', 'u', 'd')");
                        });
                });

            modelBuilder.Entity("Walrus.Infrastructure.Store.SinkCursorRow", b =>
                {
                    b.Property<string>("SinkId")
                        .HasColumnType("text")
                        .HasColumnName("sink_id");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<long>("LastSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("last_seq");

                    b.Property<NpgsqlLogSequenceNumber>("StartLsn")
                        .HasColumnType("pg_lsn")
                        .HasColumnName("start_lsn");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SinkId", "Source")
                        .HasName("pk_walrus_sink_cursors");

                    b.ToTable("walrus_sink_cursors", (string)null);
                });

            modelBuilder.Entity("Walrus.Infrastructure.Store.SinkRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.PrimitiveCollection<string[]>("Tables")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tables");

                    b.Property<string>("Target")
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id")
                        .HasName("pk_walrus_sinks");

                    b.ToTable("walrus_sinks", null, t =>
                        {
                            t.HasCheckConstraint("ck_walrus_sinks_id", "id ~ '^[a-z0-9][a-z0-9-]{0,62}$'");

                            t.HasCheckConstraint("ck_walrus_sinks_kind", "kind in ('postgres', 'index', 'webhook')");
                        });
                });

            modelBuilder.Entity("Walrus.Infrastructure.Store.DeadLetterRow", b =>
                {
                    b.HasOne("Walrus.Infrastructure.Store.SinkRow", null)
                        .WithMany()
                        .HasForeignKey("SinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_walrus_dead_letters_walrus_sinks_sink_id");
                });

            modelBuilder.Entity("Walrus.Infrastructure.Store.SinkCursorRow", b =>
                {
                    b.HasOne("Walrus.Infrastructure.Store.SinkRow", null)
                        .WithMany()
                        .HasForeignKey("SinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_walrus_sink_cursors_walrus_sinks_sink_id");
                });
#pragma warning restore 612, 618
        }
    }
}
