<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Walrus.Core/Walrus.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck" />
    <PackageReference Include="FsCheck.Xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

</Project>
